# -*- coding: utf-8 -*-
"""part1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1d7a7IM_lFCHjwj_qlAxycQ0OBJNCshT8
"""

################################################################################
#                                                                              #
# University of Roehampton, London (UK)                                        #
# YIT 19488399, Antonio Ramon Oliver                                           #
# Module: Algorithms                                                           #
# Coursework part 1 (20% value). Weeks 1 -3. Date: Monday, 25 October 2021.    #
#                                                                              #
################################################################################


# importing module for work/manage files/data
import pandas as pd

#variable for change name of the file to read
filename = "/uk_glx_open_retail_points_v20_202104.csv"


# read specific columns of csv file using Pandas
df = pd.read_csv(filename, usecols = ['long_wgs','lat_wgs'])
print(df)

#selecting one row randomly (2 values from same row)
random_row = df.sample()
print(random_row) #dispaying selection